<?php
//echo nl2br(var_export($this,true));
$spp = $this->spare_part_price;
if(!isset($spp)){
	Echo "spp var ikke sat";
}
/*echo "<br/>Url".$spp->getSpare_part_url();
echo "<br/>Name is ".$spp->getName();
echo "<br/>Spare_part_url".$spp->Spare_part_url;*/
$class_vars = get_class_methods($spp);
/*echo "UL<hr><UL>";
foreach($class_vars as $key){
	$method = $key;
	$val="";
	//$val = $spp->$method();
	echo "<li> $method $key - $val </li>";
}
echo "</UL>";
echo "<hr>";*/
$url = $spp->Spare_part_url;
//$url = 'http://jp.dk';
$return_url = "/index/details/spare_part_price_id/".$spp->Spare_part_price_id;
$return_name = $spp->Name;
echo "<a href='$return_url'>Return til $return_name </a><br>";
echo "<h3>Varen hos butikken</H3>";
if(strpos($url,'autostumper')>0){
	echo "<div class='bdp-user-warning' ><em>Webbutikken www.autostumper.dk er desværre ikke tilgængelig. <br/>Kontakt Autostumper direkte,"
			." eller find vare hos en leverandør, "
			."hvor webbutikken er aktiv.<br/><br/>mvh<br/>bildelspriser.dk</em></div>";	
}
else{
	echo "<br><a href = '".$url."' >Gå direkte til varen hos butikken</a>";
	echo "<br><iframe style='border:0px' width='100%' height='800px'  src='$url' >";
}

/*
 *    '_spare_part_price_id' => 290195,
   '_name' => NULL,
   '_description' => NULL,
   '_spare_part_url' => NULL,
   '_spare_part_image_url' => NULL,
   '_spare_part_category_id' => NULL,
   '_spare_part_category_free_text' => NULL,
   '_part_placement' => NULL,
   '_part_placement_left_right' => NULL,
   '_part_placement_front_back' => NULL,
   '_supplier_part_number' => NULL,
   '_original_part_number' => NULL,
   '_price_inc_vat' => NULL,
   '_producer_make_name' => NULL,
   '_producer_part_number' => NULL,
   '_spare_part_supplier_id' => NULL,
   '_created' => NULL,
   '_created_by' => NULL,
   '_updated' => NULL,
   '_updated_by' => NULL,
   '_mapper'
 */