<?php //echo Zend_Debug::dump($this->car_makes,'First row of words',true);

//$enum_options = html_key_val_to_options($this->enums);
global $_orderby;
$tab_index = 1;
$_orderby = $this->orderby;
echo "Sorteret efter '$_orderby' ";
function a_orderby($name,$orderby){
	global $_orderby;
	if($_orderby == $orderby)
		return $name;
	$path='/index/make-model-cleaner/orderby/'.$orderby;
	//return "<a href=?orderby=$orderby>$name</a>";
	return "<a href=$path>$name</a>";	
}
//$pp = new Bildelspriser_XmlImport_PriceParser($spp);
Zend_Loader_Autoloader::autoload('Bildelspriser_3rdParty_BilmodelDk');
include_once('Bildelspriser/3rdParty/BilmodelDk.php');
$bilmodelDk = new Bildelspriser_3rdParty_BilmodelDk();
$bilmodelDk->_loadBrands();
//car_make_id 	car_make_name 	car_make_main_id 	created 	created_by 	state 	updated 	updated_by 	state_enum
?>
<script type="text/javascript">
<!--
var active_make_id;

function callDeleteCarMake(tag_id,tag_type_id,td_status){
	td_status.innerHTML = 'Gemmer '+tag_id+' and '+tag_type_id;
	///index/ajax-html/cmd/SaveTagType/tag_id/6711/tag_type_id/14
	Http.get({		
		url: '/index/ajax-html/cmd/SaveTagType/tag_id/' + tag_id + '/tag_type_id/' + tag_type_id, 
		callback: updateInnerHtml,
		cache: Http.Cache.Get
	}, [td_status]);	
}
function deleteCarMake(car_make_id){
	if(car_make_id==null) alert("car_make_id was null");
	var td_status_name = 'td_car_make_id_'+car_make_id;
	var td_status = document.getElementById(td_status_name);
	if(td_status){
		td_status.innerHTML = "Sletter Linie "+car_make_id;
		var td_select_value = td_select[td_select.selectedIndex].value;
		Http.get({		
			url: '/index/ajax-html/cmd/DeleteCarMakeState/car_make_id/' + car_make_id, 
			callback: updateInnerHtml,
			cache: Http.Cache.Get
		}, [td_status]);
	}
	else
		alert('uable to find name '+td_name);
}	

function setCarMakeState(car_make_id,car_make_select){
	if(car_make_id==null) alert("car_make_id was null");
	var td_status_name = 'td_status_car_make_id_'+car_make_id;
	var td_status = document.getElementById(td_status_name);
	if(td_status){
		var td_select_value = car_make_select[car_make_select.selectedIndex].value;
		var td_select_text = car_make_select[car_make_select.selectedIndex].text;
		var input_hidden_car_make_state = document.getElementById('input_hidden_car_make_state_'+car_make_id);		
		if(input_hidden_car_make_state.value == td_select_text){
			td_status.innerHTML = 'Ingen ændring i Mærke Tilstand';
			return;
		}
		td_status.innerHTML = 'Setter '+car_make_id+' and '+car_make_select[car_make_select.selectedIndex].text;
		///index/ajax-html/cmd/SaveTagType/tag_id/6711/tag_type_id/14
		Http.get({		
			url: '/index/ajax-html/cmd/SetCarMakeState/car_make_id/' + car_make_id + '/state_enum/' + car_make_select[car_make_select.selectedIndex].text, 
			callback: updateInnerHtml,
			cache: Http.Cache.Get
		}, [td_status]);
		input_hidden_car_make_state.value = td_select_text;
	}
	else
		alert('uable to find name '+td_status_name);
}

function setCarMakeMainId(car_make_id,car_make_main_select){
	if(car_make_id==null) alert("car_make_id was null");	
	var td_status_name = 'td_status_car_make_id_'+car_make_id;
	var td_status = document.getElementById(td_status_name);
	if(td_status){
		var td_select_value = car_make_main_select[car_make_main_select.selectedIndex].value;
		var td_select_text = car_make_main_select[car_make_main_select.selectedIndex].text;
		var td_car_make_main_id_value = document.getElementById('td_car_make_main_id_'+car_make_id);
		if(td_car_make_main_id_value.innerHTML == td_select_value ||
			((-1 == td_select_value) && (td_car_make_main_id_value.innerHTML == '') )){
			td_status.innerHTML = 'Ingen ændring i primær mærke.';
			return;
		}
		td_status.innerHTML = 'Setter mærke '+car_make_id+' til Primær mærke id '+car_make_main_select[car_make_main_select.selectedIndex].text;
		Http.get({		
			url: '/index/ajax-html/cmd/SetCarMakeMainId/car_make_id/' + car_make_id + '/car_make_main_id/' + td_select_value, 
			callback: updateInnerHtml,
			cache: Http.Cache.Get
		}, [td_status]);
	}
	else
		alert('unable to find name '+td_status_name);
}

function showModelCleaner(car_make_id){
	var last_tr, next_tr;
	if(active_make_id!=null){
		last_tr = getModelCleanerTr(active_make_id);
		//last_tr.style = 'visibility:colapse';
		last_tr.innerHTML = null;
		active_make_id = null;
	}	
	active_make_id = car_make_id;
	next_tr = getModelCleanerTr(car_make_id);
	next_tr.innerHTML = "<td colspan=3><h2>Loading Data..</H2></td>";
	getInnerHtmlModelCleaner(car_make_id,next_tr);
}

function getInnerHtmlModelCleaner(car_make_id,element){
	Http.get({		
		url: '/index/models-cleaner/car_make_id/' + car_make_id, 
		callback: updateInnerHtml,
		cache: Http.Cache.Get
	}, [element]);	
}

function getModelCleanerTr(car_make_id){
	if(car_make_id>1)
		return document.getElementById('tr_car_make_models_id_' + car_make_id);
	else
		alert('car_make_id was '+car_make_id+' it must be an integer ');
}

function deleteCarModel(car_model_id){
	if(car_model_id==null) alert("car_model_id was null");
	var td_status_name = 'td_car_model_id_'+car_model_id;
	var td_status = document.getElementById(td_status_name);
	if(td_status){
		td_status.innerHTML = "Sletter Linie "+car_model_id;
		var td_select_value = td_select[td_select.selectedIndex].value;
		Http.get({		
			url: '/index/ajax-html/cmd/DeleteCarModelState/car_model_id/' + car_make_id, 
			callback: updateInnerHtml,
			cache: Http.Cache.Get
		}, [td_status]);
	}
	else
		alert('uable to find name '+td_name);
}	

function setCarModelState(car_model_id,car_model_select){
	if(car_model_id==null) alert("car_model_id was null");
	var td_status_name = 'td_status_car_model_id_'+car_model_id;
	var td_status = document.getElementById(td_status_name);
	var td_select_text = car_model_select[car_model_select.selectedIndex].text;
	if('Offentlig' == td_select_text || 'Slettet' == td_select_text ){
		var td_select = document.getElementById('td_car_model_main_id_select_'+car_model_id);
		td_select.innerHTML = "Offentlig - ingen må primær vælges";
	}
	if(td_status){
		var td_select_value = car_model_select[car_model_select.selectedIndex].value;
		var input_hidden_car_model_state = document.getElementById('input_hidden_car_model_state_'+car_model_id);		
		if(input_hidden_car_model_state.value == td_select_text){
			td_status.innerHTML = 'Ingen ændring i Mærke Tilstand';
			return;
		}
		td_status.innerHTML = 'Setter '+car_model_id+' and '+car_model_select[car_model_select.selectedIndex].text;
		///index/ajax-html/cmd/SaveTagType/tag_id/6711/tag_type_id/14
		Http.get({		
			url: '/index/ajax-html/cmd/SetCarModelState/car_model_id/' + car_model_id + '/state_enum/' + car_model_select[car_model_select.selectedIndex].text, 
			callback: updateInnerHtml,
			cache: Http.Cache.Get
		}, [td_status]);
		input_hidden_car_model_state.value = td_select_text;
	}
	else
		alert('uable to find name '+td_status_name);
}


function setCarModelMainId(car_model_id,select){
	if(car_model_id==null) alert("car_model_id was null");	
	var td_status_name = 'td_status_car_model_id_'+car_model_id;
	var td_status = document.getElementById(td_status_name);
	if(td_status){
		var td_select_value = select[select.selectedIndex].value;
		var td_select_text = select[select.selectedIndex].text;
		var td_car_model_main_id_value = document.getElementById('td_car_model_main_id_'+car_model_id);
		if(td_car_model_main_id_value.innerHTML == td_select_value ||
			((-1 == td_select_value) && (td_car_model_main_id_value.innerHTML == '') )){
			td_status.innerHTML = 'Ingen ændring i primær model.';
			return;
		}
		td_status.innerHTML = 'Setter model '+car_model_id+' til Primær Model id '+select[select.selectedIndex].text;
		Http.get({		
			url: '/index/ajax-html/cmd/SetCarModelMainId/car_model_id/' + car_model_id + '/car_model_main_id/' + td_select_value, 
			callback: updateInnerHtml,
			cache: Http.Cache.Get
		}, [td_status]);
	}
	else
		alert('unable to find name '+td_status_name);
}

//-->
</script>
<table class="bdp_price_all_details" >
<thead>
<tr>
	<th><?=a_orderby('Id','car_make_id');?></th>
	<th><?=a_orderby('Bilmærke','car_make_name');?></th>
	<th><?=a_orderby('Tilstand','state_enum');?></th>
	<th><?=a_orderby('Primær Nr','car_make_main_id');?></th>
	<th>Handling</th>
	<th><?=a_orderby('Primær Bilmærke','car_make_main_id');?></th>
	<th>Tilbagemelding fra Server</th></tr>
</thead>
<?php foreach ($this->car_makes as $row) : ?>
<?php $id =$row['car_make_id']; 
	$state = $row['state_enum'];
	$original = false;	
	if('Original' == $state){
		$original = true;	
	}
	 ?>
	<tr id="tr_car_make_id_<?=$row['car_make_id']?>">
		<td><?= $row['car_make_id']?></td>
		<td><a href='javascript:showModelCleaner(<?=$row['car_make_id']?>);' >
				<?= $row['car_make_name']?></a></td>
		<td>
			<select taborder='<?php echo $tab_index++; ?>>' onblur='setCarMakeState(<?php echo $id ?>,this);' 
				id='select_tag_id_<?php echo $id ?>' >
				<?=html_key_val_to_options($this->enums,$row['state_enum'],$row['state_enum'],'-Vælg tilstand');?></select>
			<input type='hidden' id='input_hidden_car_make_state_<?php echo $id ?>' value='<?=$row["state_enum"]?>'  >	
			</td>		
		<td id='td_car_make_main_id_<?=$id?>' ><?= $row['car_make_main_id']?></td>
		<td  ><button onclick="alert('delete')" >Slet</button></a></td>		
		<td ><select onblur='setCarMakeMainId(<?php echo $id ?>,this)'> 
		<?=html_key_val_to_options($this->car_make_pairs,$row['car_make_main_id'],null,'-Vælg primær mærke')?>
						</select> </td>
		<td width='200px' style='font-size: -2;' id="td_status_car_make_id_<?=$id ?>" >(status)</td>
		</tr>
	<tr id="tr_car_make_models_id_<?=$row['car_make_id']?>" >
		<!--  replace using innerHTML -->
	</tr>	
<?php endforeach; ?>
</table>