<?php //echo Zend_Debug::dump($this->car_makes,'First row of words',true);

//$enum_options = html_key_val_to_options($this->enums);
global $_orderby;
$tab_index = 1;
$_orderby = $this->orderby;
if($_orderby)
	echo "Sorteret efter '$_orderby' ";
function a_orderby($name,$orderby){
	global $_orderby;
	if($_orderby == $orderby)
		return $name;
	$path='/index/make-model-cleaner/orderby/'.$orderby;
	$path = 'javascript:alert("No sorting here");return false;';
	//return "<a href=?orderby=$orderby>$name</a>";
	return "<a href=$path>$name</a>";	
}

if(!is_array($this->car_models_pairs))	error("the view variable car_models_pair was not an array");

//car_make_id 	car_make_name 	car_make_main_id 	created 	created_by 	state 	updated 	updated_by 	state_enum
?>
<script type="text/javascript">
<!--



function callDeleteCarMake(tag_id,tag_type_id,td_status){
	td_status.innerHTML = 'Gemmer '+tag_id+' and '+tag_type_id;
	///index/ajax-html/cmd/SaveTagType/tag_id/6711/tag_type_id/14
	Http.get({		
		url: '/index/ajax-html/cmd/SaveTagType/tag_id/' + tag_id + '/tag_type_id/' + tag_type_id, 
		callback: updateStatus,
		cache: Http.Cache.Get
	}, [td_status]);	
}


//-->
</script><td colspan=6>
<table class="bdp_price_all_details" >
<thead>
<tr>
	<th><?=a_orderby('Id','car_make_id');?></th>
	<th><?=a_orderby('Model','car_make_name');?></th>
	<th><?=a_orderby('Renset<br/>Model Navn','state_enum');?></th>
	<th><?=a_orderby('Hoved<br/>Id','car_model_main_id');?></th>
	<th>Handling</th>
	<th><?=a_orderby('Primær Bilmærke','car_model_main_name');?></th>
	<th>Tilbagemelding fra Server</th></tr>
</thead>
<?php foreach ($this->car_models as $row) : ?>
<?php $id =$row['car_model_id']; //Zend_Debug::dump($row,'Row',true);
		/*Row array(7) {
		  ["car_make_id"] => int(146)
		  ["car_make_name"] => string(3) "CMA"
		  ["car_model_id"] => int(1472)
		  ["car_model_name"] => string(6) "Passat"
		  ["model_cleansed_name"] => string(6) "Passat"
		  ["state_enum"] => NULL
		  ["car_model_main_id"] => NULL */
	$state = $row['state_enum'];
	$original = false;	
	if('Original' == $state){
		$original = true;	
	}
?>
	<tr id="tr_car_model_id_<?=$row['car_model_id']?>">
		<td><?= $row['car_model_id']?></td>
		<td><?= $row['car_model_name']?></td>
		<td><?= $row['model_cleansed_name']?></td>
		<td>
			<select taborder='<?php echo $tab_index++; ?>' onblur='setCarModelState(<?php echo $id ?>,this);' 
				id='select_tag_id_<?php echo $id ?>' >
				<?=html_key_val_to_options($this->enums,$row['state_enum'],$row['state_enum'],'-Vælg tilstand');?></select>
			<input type='hidden' id='input_hidden_car_model_state_<?php echo $id ?>' value='<?=$row["state_enum"]?>'  >	
			</td>		
		<td id='td_car_model_main_id_<?=$id?>' ><?= $row['car_model_main_id'] ?></td>
		<td  ><button onclick="alert('delete')" >Slet</button></td>		
		<td id='td_car_model_main_id_select_<?php echo $id ?>' >
			<select onblur='setCarModelMainId(<?php echo $id ?>,this)'> 
		<?=html_key_val_to_options($this->car_models_pairs,$row['car_model_main_id'],null,'-Vælg primær model');?>
						</select> </td>
		<td width='200px' style='font-size: -2;' id="td_status_car_model_id_<?=$id ?>" >(status)</td>
		</tr>

<?php endforeach; ?>
</table></td>