<H2>Bildelspriser.dk - den eneste seriøse prisdatabase til reservedele</H2>
Vores site indeholder nu rigtige priser, fra flere forskellige butikker.<br/>
Vi arbejder løbende på at få flere priser ind fra de forskellige butikker. <br/>
<br/>
Har du data du ønsker at få lagt på sitet skal du kontakte os pr. telefon 40 86 81 18.
<br/>
<a href="/index/index/">Tryk her for at komme tilbage til vores søgemaskine!</a><br/>
<br/>
Tak fordi du kiggede forbi.
<br/>
mvh<br/>
<br/>
<a href="http://bildelspriser.dk/" >bildelspriser.dk</a><br/>
Holmekrogen 26<br/>
2830 Virum<br/>
Tel: 40 86 81 18<br/>
