<?php
// Disable layouts
$this->layout()->disableLayout();
$html_debug = false;
if(array_key_exists('debug',$this->params)){
	$html_debug = true;
	echo "<H1>Parameters</H1><table border=1><tr><td>Parameter</td><td>value</td>";
	foreach($this->params as $key=>$val){
		echo "<tr><td>$key</td><td>$val</td></td>";
	}
	echo "</table>";	
	$this->model->setDebug();
}

// Fetch results from the model; again, merely illustrative
$results = $this->model->query($this->params);

//var_dump($this->request->getParams());  

// Now, create a Zend_Dojo_Data object.
// The first parameter is the name of the field that has a
// unique identifier. The second is the dataset. The third
// should be specified for autocompletion, and should be the
// name of the field representing the data to display in the
// dropdown. Note how it corresponds to "name" in the 
// AutocompleteReadStore.

if($html_debug)
	$data = "<br>Result was " . var_export($results,true);
else	
	$data = new Zend_Dojo_Data('id', $results, 'name');

// Send our output
echo $data;
