<H2>Bildelspriser.dk - den eneste seriøse prisdatabase til reservedele</H2>
Vores site indeholder nu rigtige priser, fra flere forskellige butikker.</br>
Vi arbejder løbende på at få flere 
Vores site er ved at bliver udviklet færdigt, sammen med vores dataopsamling.<br/>
De priser der ligger i vores database er rigtige priser,<br/>
men der udestår stadig en del med at få lavet alt, som vi gerne vil have det.<br/>
<br/>
Sitet lanceres officielt d. 1. Januar 2011.  <br/>
<br/>
Har du data du ønsker at få lagt på sitet skal du kontakte os pr. telefon 40 86 81 18.
<br/>
<a href="/index/index/">Tryk her for at komme tilbage til vores søgemaskine!</a><br/>
<br/>
Tak fordi du kiggede forbi.
<br/>
mvh<br/>
<br/>
<a href="http://bildelspriser.dk/" >bildelspriser.dk</a>
Holmekrogen 26<br/>
2830 Virum<br/>
Tel: 40 86 81 18<br/>
