<h1>Find bildele via Bilmærke og Model</h1>
<?php
// Disable layouts
$back_text = "[tilbage]";
//$this->layout()->disableLayout();
$html_debug = true;
if(array_key_exists('debug',$this->params)){
	$html_debug = true;
	echo "<H1>Parameters</H1><table border=1><tr><td>Parameter</td><td>value</td>";
	foreach($this->params as $key=>$val){
		echo "<tr><td>$key</td><td>$val</td></td>";
	}
	echo "</table>";	
	$this->model->setDebug();
}

// Fetch results from the model; again, merely illustrative
$results = $this->model->query('');
$id="";
$name="";
$mod_id="";
$mod_name="";
$car_make_link = "";
$car_model_link = "";
$page_link = "/index/brands";
if(!array_key_exists('brand',$this->params)){
	echo "<h3>V&aelig;lg dit bilmærke</h3>";
	foreach($results as $ar_brand){
		$id = $ar_brand['id'];
		$name = $this->dkText($ar_brand['name']);
		$car_make_link = "$page_link/brand/$name/car_make_id/$id";
		echo " <a href='$car_make_link' >$name</a> &nbsp; <br/> <span id='car_make_".$id."_info' ></span>";
	}
}else{
	$brand = urldecode($this->params['brand']);
	$cmi = urldecode($this->params['car_make_id']);
	$car_make_link = "$page_link/car_make_id/$cmi";
	echo "Du har valgt  <a href='$car_make_link' title='Find priser på Reservedele og bildele til $brand' > <br>Mærke: <b>$brand</b> </a> <a href='$page_link'>$back_text</a><br/>";
	$this->headTitle()->append($brand); 
	$id = $cmi;
	$name = $brand;
	$car_make_link = "$page_link/brand/$name/car_make_id/$id";
	if(!array_key_exists('car_model_id',$this->params)){
		$res = $this->car_model->query($this->params);
		if(sizeof($res)==0)
		{
			echo "<br/>Der var ingen modeller";
		}
		echo "<H2>V&aelig;lg en bilmodel</h2>";
		foreach($res as $ar_brand){
			$_model_name = $ar_brand['name'];
			$_model_id = $ar_brand['id'];
			$car_model_link = $car_make_link."/car_model_id/$_model_id/";
			echo " <a href='$car_model_link' >$_model_name <span class='alt_models'  id='alt_models_$_model_id' ></span> <span class='price_info' id='prices_info_$_model_id'  ></span> </a> &nbsp; <br/>   ";
		}
	}
	else{
		$mod_id=$this->params['car_model_id'];
		$cmo_mapper = MapperFactory::getCmoMapper();
		/** @var $cmo_rowset Zend_Db_Table_Rowset */
		$cmo_rowset = $cmo_mapper->find($mod_id);
		//Zend_Debug::dump($cmo_rowset,'CMO OBJ',true);
		if($cmo_rowset->count()==0){
			echo "Ukendt model nummer. $mod_id  ";
			return;
		}
		$ar_car_model = $cmo_rowset->current()->toArray();
		$mod_name=$ar_car_model['car_model_name'];
		$car_model_link = $car_make_link."/car_model_id/$mod_id/car_model_name/$mod_name";
		echo " <a href='$car_model_link' title='Find priser på Reservedele og bildele til $brand $mod_name' > Model: <b>".$mod_name."</b></a>   <a href='$car_make_link'>$back_text</a><br/>";		
	}
}

if($mod_id>0){
	echo "<h3>Bildele til $brand $mod_name</h3>";
	$this->headTitle()->append($mod_name);
	$meta_desc = 'Billige reservedele til '.$name.' '.$mod_name;
	$meta_keywords = 'billigste reservedele bildele tilbehør styling billige autodele';
	$this->headMeta()->prependName('description',$meta_desc);
	$this->headMeta()->prependName('keywords',$meta_keywords);	
	$url='/index/newsearch/car_model_id/'.$mod_id;
	Zend_View_Helper_SparePartPricePrinter::$car_model_id = $mod_id;
	//echo "<iframe src='$url' width='100%' height='600px' >";
}

if(!$this->prices and $this->all_names){
	/*    'supplier_name' =&gt; 'Autostumper',
		  'car_make_name' =&gt; 'Alfa Romeo',
		  'car_model_name' =&gt; '145',
		  'car_model_id' =&gt; 1155,
		  'spare_part_price_id' =&gt; 418178,
		  'name' =&gt; 'DENSO TÆNDRØR FLERE',
		  'description' =&gt; '1,6ie AR33201',
		  'spare_part_url' =&gt; 'http://www.autostumper.dk/shop/productinfo.asp?id=Q00046',
		  'spare_part_image_url' =&gt; 'http://www.autostumper.dk/shop/productinfo.asp?id=Q00046',
		  'spare_part_category_id' =&gt; NULL,
		  'spare_part_category_free_text' =&gt; NULL,
		  'part_placement' =&gt; NULL,
		  'part_placement_left_right' =&gt; NULL,
		  'part_placement_front_back' =&gt; NULL,
		  'supplier_part_number' =&gt; 'Q00046',
		  'original_part_number' =&gt; NULL,
		  'price_inc_vat' =&gt; '21.00',
		  'producer_make_name' =&gt; NULL,
		  'producer_part_number' =&gt; '0',
		  'spare_part_supplier_id' =&gt; 6,
		  'year_from' =&gt; NULL,
		  'month_from' =&gt; NULL,
		  'year_to' =&gt; NULL,
		  'month_to' =&gt; NULL,
		  'chassis_no_from' =&gt; NULL,
		  'chassis_no_to' =&gt; NULL, */
	echo "<ul>";
	$current_url = $_SERVER["REDIRECT_URL"];
	foreach($this->all_names as $obj){
		$name = utf8_decode($obj['name']);
		$q=utf8_encode(first_word($name));// not ulrencoded anymore
		$q=trim($q,'.,-');
		$url = str_replace('//','/',$current_url.'/q/'.$q);
		echo "<li><a href='$url' > ". utf8::right_code($name)."</a></li>";	
		
		}
	echo "<ul/>";
}

if($this->prices){
	$table = "<table class='bdp_std_table' >";
	$table .= "<tr><th>Bildele fundet med søgningen '$this->q'<th><tr>";
	$tr_class = "";
	$id = 1;
	foreach ($this->prices as $price) {
		$tr_class = ($id++%2==0) ? 'odd' : 'even';	
		$table.='<tr id="spp_id_'.$price['spare_part_price_id'].'"  class="'.$tr_class.'" >'
				.'<td>'.$this->sparePartPricePrinter($price)
				.'</td></tr>';
	}  
	echo $table.'</table>';
}
//echo "</table>"
// Send our output

?>
<script type="text/javascript"   >
<!--
 function iframe_loaded(iframe_obj_list,event_name){
	var iframe_obj = iframe_obj_list[0];
	alert('iframe event '+event_name);
	var content = iframe_obj.innerHTML;
	alert(content);
};

function set_span(text,span_id){
	jQuery('#'+span_id)[0].innerHTML = text;
}

function erich_price_span_by_model_id(index,span_obj){
	var span_id = span_obj.id;
	var car_model_id = span_id.replace('prices_info_','');
	jQuery('#'+span_id).load('/index/ajax-html/cmd/GetPriceCountByModel/car_model_id/'+car_model_id);
//	span_obj.innerHTML = ' - '+car_model_id;
}

function erich_model_span_by_model_id(index,span_obj){
	var span_id = span_obj.id;
	var car_model_id = span_id.replace('alt_models_','');
	span_obj.innerHTML = ' - '+car_model_id;
}

 
jQuery(document).ready(function(){ 
	jQuery('.price_info').each(erich_price_span_by_model_id);
});
//-->
</script>