<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
    <title>SOAP Test</title>
   </head>
<body>
  
<table>
	<tr>
		<th>Add result:</th>
		<td><?php echo $this->add_result;?></td>
	</tr>
	<tr>
		<th>Logical not result:</th>
		<td><?php echo var_dump($this->logical_not_result);?></td>
	</tr>
	<tr>
		<th>Sort result:</th>
		<td><?php echo var_dump($this->sort_result);?></td>
	</tr>
	<tr>
		<th>Text Result:</th>
		<td><? echo var_dump($this->text_result)?></td>
	</tr>
</table>
</body>
</html>