<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<LINK REL=StyleSheet HREF="/bdp/public/css/b2b_user.css" TYPE="text/css" MEDIA=screen>
<title>bdp-title</title>
	<style type="text/css"   ></style>
</head>
<h2>Please login?</h2>
<?php echo $this->form;

echo "<br>";
echo var_export($this,true);
echo "<h3>".$this->error_message."</h3>";
?>
